// const myDate= new Date()
// console.log(myDate.toString())
// console.log(myDate.toDateString())
// console.log(myDate.toISOString())
// console.log(myDate.toJSON())
// console.log(myDate.toLocaleString())
// console.log(typeof(myDate))

let myCreatedDate= new Date("2024-07-20")
console.log(myCreatedDate.toString())
let myNewCreatedDate = new Date("07-20-2024")
console.log(myNewCreatedDate.toLocaleDateString())
